AER-333 Throw correct exception when polygon is not closed
aerius/IMAER-java pull request #106
Opened 2022-06-02 14:42 UTC by wtenbosch

When a polygon is not closed, an `IllegalArgumentException` is thrown by JTS which is converted to a AeriusException with reason Internal Error. This change catches the IllegalArgumentException and converts it to a AeriusException with reason "The GML contains an invalid geometry", and includes the offending emission source ID.

2022-06-02 14:53 UTC, BertScholten approved these changes
LGTM

2022-06-02 14:55 UTC, BertScholten requested changes
Oh, missed that the build is now failing due to a unittest

2022-06-02 15:34 UTC, BertScholten approved these changes
LGTM

2022-06-02 15:39 UTC, merged

2022-06-08 09:13 UTC, Hilbrand commented
@wtenbosch Please do not make branches in this repository! And if you do (accidental) delete the branch after it's merged!

2022-06-08 09:19 UTC, wtenbosch commented
Ah I see, had the wrong origin configured still. Never had made any PRs for IMAER-java