AER-1379 add single scenario type
aerius/IMAER-java pull request #186
Opened 2023-03-01 15:47 UTC by Gijsvanhorn

and add min and max situation validation information

2023-03-01 16:18 UTC, BertScholten commented on source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationJobType.java
> +    this.maximumNumberOfSituations = maximumNumberOfSituations;
Not sure what the point of these are, and if it makes sense to keep them in this enum: minimum is always 1, and maximum isn't as strict for things like `IN_COMBINATION_PROCESS_CONTRIBUTION` is it? Isn't it usually a situation type that should be at most 1 in a calculation job?

2023-03-01 16:42 UTC, Hilbrand requested changes
This is not the right approach. The limit of 6 is also just an arbitrary limit made for the user interface, which should no tbe hardcoded in this library. I suggest to close this pr and add implement the checks in connect server. Put them in a separate validation class that checks for these limits.

2023-03-02 09:05 UTC, Gijsvanhorn commented
I removed the number of situations from the enum, and am doubting whether to remove the other validation rules as well. This PR is still relevant because it adds the SINGLE_SITUATION job type though.

2023-03-02 10:15 UTC, BertScholten approved these changes
LGTM

2023-03-02 10:15 UTC, BertScholten commented on source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationJobType.java
> +   * <p>
I don't really mind this, but we don't use these tags that often and it does seem inconsistent with the other javadocs in this enum.

2023-03-02 14:33 UTC, Hilbrand approved these changes
LGTM. Other validations can be left in.They specify something about the CalculationJobType.

2023-03-02 14:33 UTC, merged